// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Supabase cannot auto-create shadow DBs; set SHADOW_DATABASE_URL to a second empty DB for migrate dev.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
