// app/api/woocommerce/abandoned-cart/route.ts
//
// Ingestion endpoint for the "CartRenew for WooCommerce" WordPress plugin.
// The plugin POSTs here (see includes/class-cr-api.php) whenever its WP-Cron
// sweep finds a cart that's been inactive past the configured wait time,
// with a phone number and consent on file.
//
// Auth: Authorization: Bearer <api_key>  — the api_key must match the
// `stores.api_key` column for the given `store_id`. store_id itself is the
// existing CartRenew store UUID (shown in the merchant dashboard) — it is
// NOT generated by this endpoint, only verified.

import { NextRequest, NextResponse } from 'next/server'
import { supabaseAdmin } from '@/lib/supabase'
import { triggerWhatsAppRecoveryForCart } from '@/lib/services/messaging'

export const dynamic = 'force-dynamic'
export const runtime = 'nodejs'

interface WooCommerceCartItem {
  name: string
  quantity: number
  price: number | string
}

interface WooCommerceAbandonedCartPayload {
  store_id: string
  cart_key: string
  customer_name?: string | null
  phone_number: string
  cart_total: number | string
  checkout_url: string
  cart_contents: WooCommerceCartItem[]
  site_url?: string
}

export async function POST(req: NextRequest) {
  // --- 1. Auth ---------------------------------------------------------
  const authHeader = req.headers.get('authorization') || ''
  const apiKey = authHeader.startsWith('Bearer ')
    ? authHeader.slice('Bearer '.length).trim()
    : null

  if (!apiKey) {
    return NextResponse.json(
      { error: 'Missing Authorization: Bearer <api_key> header.' },
      { status: 401 }
    )
  }

  let payload: WooCommerceAbandonedCartPayload
  try {
    payload = await req.json()
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body.' }, { status: 400 })
  }

  const { store_id, cart_key, phone_number, checkout_url, cart_contents } = payload

  if (!store_id || !cart_key || !phone_number || !checkout_url) {
    return NextResponse.json(
      { error: 'store_id, cart_key, phone_number and checkout_url are required.' },
      { status: 400 }
    )
  }

  // stores has no `name` column — only select fields that exist.
  const { data: store, error: storeError } = await supabaseAdmin
    .from('stores')
    .select('id, api_key')
    .eq('id', store_id)
    .maybeSingle()

  if (storeError || !store) {
    return NextResponse.json({ error: 'Unknown store_id.' }, { status: 404 })
  }

  if (!store.api_key || store.api_key !== apiKey) {
    return NextResponse.json({ error: 'Invalid API key for this store.' }, { status: 401 })
  }

  // --- 2. Idempotency: don't double-send for the same cart -------------
  // external_cart_key is a generic column (platform + cart_key combined)
  // so WooCommerce, Shopify, and future platforms share abandoned_carts.
  const externalCartKey = `woocommerce:${store_id}:${cart_key}`

  const { data: existing } = await supabaseAdmin
    .from('abandoned_carts')
    .select('id, status')
    .eq('external_cart_key', externalCartKey)
    .maybeSingle()

  // Schema check: status ∈ pending | messaged | recovered | lost | opted_out
  // (not "sent" — that was a mismatch with the live CHECK constraint)
  if (existing?.status === 'messaged') {
    return NextResponse.json({ status: 'already_sent' }, { status: 200 })
  }

  if (existing && existing.status !== 'pending') {
    return NextResponse.json({ status: 'already_processed' }, { status: 200 })
  }

  const cartValue = Number(payload.cart_total) || 0
  const items = (cart_contents || []).map((item) => ({
    name: item.name,
    title: item.name,
    quantity: Number(item.quantity) || 1,
    price: Number(item.price) || 0,
  }))

  let cartId = existing?.id

  if (!cartId) {
    // shopify_cart_token is NOT NULL on legacy schema — fill with the Woo
    // external key so the (store_id, shopify_cart_token) unique index stays valid.
    const { data: inserted, error: insertError } = await supabaseAdmin
      .from('abandoned_carts')
      .insert({
        store_id,
        platform: 'woocommerce',
        external_cart_key: externalCartKey,
        shopify_cart_token: externalCartKey,
        customer_name: payload.customer_name || null,
        customer_phone: phone_number,
        checkout_url,
        cart_value: cartValue,
        items,
        status: 'pending',
      })
      .select('id')
      .single()

    if (insertError || !inserted) {
      console.error('CartRenew WooCommerce: failed to insert abandoned cart', insertError)
      return NextResponse.json({ error: 'Failed to record cart.' }, { status: 500 })
    }
    cartId = inserted.id
  }

  // Atomically move this cart out of "pending" before dispatch. This also
  // excludes the fallback cart-recovery cron, which claims pending rows.
  const processingStartedAt = new Date().toISOString()
  const { data: claimed, error: claimError } = await supabaseAdmin
    .from('abandoned_carts')
    .update({
      status: 'messaged',
      processing_started_at: processingStartedAt,
    })
    .eq('id', cartId)
    .eq('status', 'pending')
    .is('processing_started_at', null)
    .select('id')
    .maybeSingle()

  if (claimError) {
    console.error('CartRenew WooCommerce: failed to claim abandoned cart', claimError)
    return NextResponse.json({ error: 'Failed to claim cart.' }, { status: 500 })
  }

  if (!claimed) {
    return NextResponse.json({ status: 'already_processing' }, { status: 200 })
  }

  // --- 3. Send the WhatsApp recovery message ----------------------------
  // triggerWhatsAppRecoveryForCart returns { sent, error } — it does not throw
  // on soft send failures, so check result.sent explicitly.
  try {
    const result = await triggerWhatsAppRecoveryForCart({
      storeId: store_id,
      cartId,
      customerPhone: phone_number,
      customerName: payload.customer_name || null,
      checkoutUrl: checkout_url,
      cartValue,
      items,
      customerEmail: null,
      cartToken: cart_key,
    })

    if (!result.sent) {
      // Keep pending so /api/cart-recovery cron can retry. No "send_failed" status
      // exists in the CHECK constraint.
      await supabaseAdmin
        .from('abandoned_carts')
        .update({ status: 'pending', processing_started_at: null })
        .eq('id', cartId)
        .eq('status', 'messaged')
        .eq('processing_started_at', processingStartedAt)

      return NextResponse.json(
        { error: result.error || 'WhatsApp send failed.', status: 'pending' },
        { status: 502 }
      )
    }

    // messaging.ts already sets status=messaged + message_sent_at on success;
    // reinforce message_sent_at for clarity (column is message_sent_at, not sent_at).
    await supabaseAdmin
      .from('abandoned_carts')
      .update({
        status: 'messaged',
        message_sent_at: new Date().toISOString(),
        processing_started_at: null,
      })
      .eq('id', cartId)
      .eq('status', 'messaged')
      .eq('processing_started_at', processingStartedAt)

    return NextResponse.json({ status: 'sent', result }, { status: 200 })
  } catch (err) {
    console.error('CartRenew WooCommerce: WhatsApp send failed', err)

    await supabaseAdmin
      .from('abandoned_carts')
      .update({ status: 'pending', processing_started_at: null })
      .eq('id', cartId)
      .eq('status', 'messaged')
      .eq('processing_started_at', processingStartedAt)

    return NextResponse.json({ error: 'WhatsApp send failed.' }, { status: 502 })
  }
}
