api_version = "2026-04"

[[extensions]]
# Change the merchant-facing name of the extension in locales/en.default.json
name = "t:name"
handle = "cartrenew-app-home"
type = "ui_extension"
uid = "2976ca65-4387-1b4f-12c2-e4ede9ecc464c724fc3b"

# Only 1 target can be specified for each app-home extension
[[extensions.targeting]]
module = "./src/AppHome.jsx"
target = "admin.app.home.render"
assets = "./assets"
