ALTER TABLE "Cart"
ADD COLUMN "detectedLang" TEXT NOT NULL DEFAULT 'HINGLISH',
ADD COLUMN "confidenceScore" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN "activeChannel" TEXT NOT NULL DEFAULT 'WHATSAPP';
